[package]
name = "kroma-witnessgen"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "native_host_runner"
path = "bin/native_host_runner.rs"

[[bin]]
name = "witness_gen_server"
path = "bin/witness_gen_server.rs"

[dependencies]
kona-host = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }

# server
dotenv.workspace = true
jsonrpc-http-server.workspace = true
jsonrpc-core.workspace = true
tracing-subscriber.workspace = true
